### ISSUE TITLE
Problem with multiple flights displaying

### ISSUE THREAD

**Issue by Alx-937** [vloss3/wizz-aycf-route-finder#6]
When multiple flights are available on the search date, only one flight is displaying.

Extension:
<img width="565" alt="Снимок экрана 2024-10-11 в 15 21 12" src="https://github.com/user-attachments/assets/699d13f7-348c-45c9-9394-d7e2aeab63ce">
Standart search:
<img width="977" alt="Снимок экрана 2024-10-11 в 15 22 00" src="https://github.com/user-attachments/assets/0517bd7e-f51a-4583-9977-d5b76e8b9d30">

**Comment by vloss3** [comment]
thanks, fixed in 1.1.5 (might take a day or two to update on Chrome Web Store)
